agribalyse:
  target: dev
  outputs:
    dev:
      type: snowflake

      # secrets — viennent du .env en local, de GitHub Secrets en CI
      account: "{{ env_var('SNOW_ACCOUNT') }}"
      user: "{{ env_var('SNOW_USER') }}"
      password: "{{ env_var('SNOW_PASSWORD') }}"

      # configuration — en clair, à compléter
      role: TRANSFORMAGRIBALYSE
      warehouse: WH_AGRIBALYSE
      database: DATABASE_AGRIBALYSE
      schema: STAGING

      threads: 4
      client_session_keep_alive: false
      query_tag: dbt_agribalyse

    ci:
      type: snowflake

      # secrets — viennent du .env en local, de GitHub Secrets en CI
      account: "{{ env_var('SNOW_ACCOUNT') }}"
      user: "{{ env_var('SNOW_USER') }}"
      password: "{{ env_var('SNOW_PASSWORD') }}"

      # configuration — en clair, à compléter
      role: TRANSFORMAGRIBALYSE
      warehouse: WH_AGRIBALYSE
      database: DATABASE_AGRIBALYSE
      schema: CI

      threads: 4
      client_session_keep_alive: false
      query_tag: dbt_agribalyse