name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dbt-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dbt_project
    env:
      SNOW_ACCOUNT: ${{ vars.SNOW_ACCOUNT }}
      SNOW_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_CI_PRIVATE_KEY }}
      SNOW_PRIVATE_KEY_PATH: /tmp/sf_ci.p8
    steps:
      - uses: actions/checkout@v4
      - run: echo "Déclenché par ${{ github.event_name }}"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.12"
      - run: pip install -r ../requirements.txt
      - run: dbt --version
      - run: dbt deps
      - name: Écrire la clé privée 
        run: |
          # préserver les retours à la ligne
          printf '%s' "$SNOW_PRIVATE_KEY" > "$SNOW_PRIVATE_KEY_PATH"
          chmod 600 "$SNOW_PRIVATE_KEY_PATH"
          head -1 "$SNOW_PRIVATE_KEY_PATH"
      - run: dbt debug --target ci
      - name: dbt build 
        run: dbt build --target ci
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dbt-target
          path: dbt_project/target/   